module.exports = {
	login_error: 'error_message_invalid_email_or_password',
	login: 'ok',
	not_authenticate: 'User not authenticated',
	not_found: 'Not found',
	nothing_updated: 'nothing_updated',
	nothing_deleted: 'nothing_deleted',
	email_err: "error_message_email_already_busy",
	perm_err: 'Permission denied',
	not_auth: 'error_message_not_authorized',
	forbidden: 'error_message_not_permission',
	user_exist_err: 'No such user',
	check_registration: 'check_registration',
	registration_checked: 'signup_checked',
	user_not_verified: 'error_message_user_not_verified',
	pass_already_changed: 'error_message_password_already_changed',
	check_forgot: 'Please confirm Email',
	password_changed: 'password_changed',
	error_message_refreshToken: 'error_message_invalid_refreshToken',
	created: 'Created',
	updated: 'Updated',
	deleted: 'Deleted',
	already_answered_question: 'You are already answer this question',
	no_such_question: 'No such question',
};
